# pyproject.toml

# Configuração do Black (Formatador)
[tool.black]
line-length = 88
target-version = ['py311']

# Configuração do Mypy (Checador de Tipos)
[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true 

# Configuração do Flake8 (Linter)
[tool.flake8]
max-line-length = 88
extend-ignore = "E203"